name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    environment: flask-testing
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Set Up Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Tests
      env:
        FLASK_ENV: testing
        DB_URI_TEST: ${{ secrets.DB_URI_TEST }}
        IBR_EMAIL: ${{ secrets.IBR_EMAIL }}
        IBR_EMAIL_PASSWORD: ${{ secrets.IBR_EMAIL_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        cd src
        python -m unittest discover -s tests/ -v
    - name: Style Check
      run: |
        cd src
        flake8 --ignore=E402 .